version: '3.4'

services: 
  api:
    build: ./bee_build
    image: ${SERVICE_NAME}
    container_name: ${SERVICE_NAME}
    volumes:
      - gosrc:/go
      - .:/go/src/${API_BASE_DIR}/${API_NAME}
    env_file: 
      - .env
    ports: 
      - "${PORT}:${PORT}"
    environment:
      - PLAN_ADQUISICIONES_CRUD_HTTP_PORT=${PORT}
      - API_NAME=${API_NAME}
      - PLAN_ADQUISICIONES_CRUD_PG_USER=${POSTGRES_USER}
      - PLAN_ADQUISICIONES_CRUD_PG_PASS=${POSTGRES_PASSWORD}
      - PLAN_ADQUISICIONES_CRUD_PG_HOST=${POSTGRES_HOST}
      - PLAN_ADQUISICIONES_CRUD_PG_DB=${POSTGRES_DB}
      - PLAN_ADQUISICIONES_CRUD_PG_SCHEMA=plan_adquisiciones
      - PLAN_ADQUISICIONES_CRUD_RUN_MODE=dev
      - RUN_MODE=dev 
      - PLAN_ADQUISICIONES_CRUD_MONGO_HOST=${MONGO_HOST}
      - PLAN_ADQUISICIONES_CRUD_MONGO_PORT=${MONGO_PORT}
      - PLAN_ADQUISICIONES_CRUD_MONGO_DB=${MONGO_DB}
      - PLAN_ADQUISICIONES_CRUD_MONGO_USER=${MONGO_USER}
      - PLAN_ADQUISICIONES_CRUD_MONGO_PASS=${MONGO_PASS}
      - PLAN_ADQUISICIONES_CRUD_MONGO_AUTH=${MONGO_AUTH}
      - SERVICE_TAGS=traefik.enable=true,traefik.frontend.entryPoints=http,traefik.frontend.rule=Host:${SERVICE_NAME}.localhost   
    command: sh -c 'cd ${API_BASE_DIR}/${API_NAME};go get -v -u ./...; bee migrate -driver=postgres -conn="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}?sslmode=disable&search_path=public" || true; go mod init ; bee run'
    depends_on: 
      - db
      - db_mongo
    networks: 
      - back_end
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:10-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks: 
      - back_end
  
  db_mongo:
    image: mongo:latest
    container_name: ${MONGO_HOST}
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGO_PORT}:27017 
    networks: 
      - back_end
  
  mongoexpress:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - 8090:8081
    depends_on:
      - db_mongo
    networks: 
      - back_end

volumes:
  gosrc:
  postgres_data:
  mongo_data:
networks: 
  back_end:
    external: true