version: '3.4'

services:

  api:
    build: ./bee_build
    volumes:
      - gosrc:/go
      - .:/go/src/${API_BASE_DIR}/${API_NAME}
    environment:
      - SERVICE_TAGS=traefik.enable=true,traefik.frontend.entryPoints=http,traefik.frontend.rule=Host:${API_NAME}.localhost
    ports:
      - '${PLAN_ADQUISICIONES_CRUD_HTTP_PORT}:${PLAN_ADQUISICIONES_CRUD_HTTP_PORT}'
    command: >
      sh -c 'cd ${API_BASE_DIR}/${API_NAME};
      go get -v;
      bee migrate -driver=postgres -conn="postgres://${PLAN_ADQUISICIONES_CRUD_PGUSER}:${PLAN_ADQUISICIONES_CRUD_PGPASS}@${PLAN_ADQUISICIONES_CRUD_PGHOST}:${PLAN_ADQUISICIONES_CRUD_PGPORT}/${PLAN_ADQUISICIONES_CRUD_PGDB}?sslmode=disable&search_path=public" || true;
      bee run -downdoc=true -gendoc=true'
    depends_on:
      - postgres
      - mongo
    networks:
      - back_end

  postgres:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - back_end

  mongo:
    image: mongo:4
    volumes:
      - mongo_data:/data/db
    networks:
      - back_end

  mongoexpress:
    image: mongo-express
    ports:
      - ${ME_HTTP_PORT}:8081
    depends_on:
      - mongo
    networks:
      - back_end

volumes:
  gosrc:
  postgres_data:
  mongo_data:
networks:
  back_end:
    external: true
